vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<C-p>", ":Git push -u origin ", opts)
vim.keymap.set("n", "<C-a>", ":Git add ", opts)
vim.keymap.set("n", "<C-c>", function()
    local input = vim.fn.input("Commit message: ")
    vim.cmd('Git commit -m "' .. input .. '"')
end)

vim.keymap.set("n", "<C-g>", function()
    vim.cmd(":Git add .")
    local input = vim.fn.input("Commit message: ")
    vim.cmd('Git commit -m "' .. input .. '"')
    vim.cmd(":Git push -u origin main")
end)
