vim.g.mapleader = " "
vim.keymap.set("i", "<C-d>", "<Esc>")
vim.keymap.set("n", "<F1>", "")
vim.keymap.set("i", "<F1>", "")
vim.keymap.set("v", "K", "")
vim.keymap.set("n", "K", "<C-u>")
vim.keymap.set("n", "J", "<C-d>")
vim.keymap.set("i", "<C-l>", "<Esc><C-w>l")
vim.keymap.set("i", "<C-h>", "<ESC><C-w>h")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("i", "<F10>", "<c-g>u<ESC>[s1z=`]a<c-g>u")
